name: Daily Bursary Update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Generate bursary pages
        run: node generate-pages.js

      - name: Generate Homepage
        run: node scripts/generate-homepage.js

      - name: Generate Sitemap
        run: node generate-sitemap.js

      - name: Create public folder
        run: |
          rm -rf public
          mkdir -p public/bursaries
          mkdir -p public/assets

      - name: Copy site files
        run: |
          cp -r public/* public/ || true
          cp index.html public/ || true
          cp -r assets public/ || true
          touch public/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
